version: '3.9'

services:
  django:
    image: restapi:0.0.2
    build: .
    command: python manage.py runserver 0.0.0.0:8000 && python manage.py migrate
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    build: postgresql
    image: restapi_postgresql:1.0.0
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  pgadmin:
    build: pgadmin
    image: restapi_pgadmin:1.0.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "84:80"