# Generated by Django 4.1.7 on 2023-03-18 17:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt_create', models.DateTimeField(auto_now_add=True)),
                ('dt_update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('proteins', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
