# Generated by Django 4.1.7 on 2023-03-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='uuid',
            new_name='id',
        ),
    ]
