# Generated by Django 4.1.7 on 2023-03-18 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_rename_uuid_products_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt_create', models.DateTimeField(auto_now_add=True)),
                ('dt_update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('proteins', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbohydrates', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='products',
            old_name='id',
            new_name='uuid',
        ),
    ]
