# Generated by Django 4.1.7 on 2023-03-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_remove_products_recipe_recipes_composition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='composition',
        ),
        migrations.AddField(
            model_name='products',
            name='recipes',
            field=models.ManyToManyField(to='Products.recipes'),
        ),
    ]
