# Generated by Django 4.1.7 on 2023-03-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_remove_recipes_composition_products_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipes',
            name='composition',
            field=models.ManyToManyField(to='Products.products'),
        ),
    ]
