# Generated by Django 4.1.7 on 2023-03-19 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_remove_recipes_calories_remove_recipes_carbohydrates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodal',
            name='product_uuid',
        ),
        migrations.AddField(
            model_name='productmodal',
            name='product_uuid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Products.products'),
        ),
    ]
