# Generated by Django 4.1.7 on 2023-03-19 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_alter_productmodal_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodal',
            name='product_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.products'),
        ),
    ]
