# Generated by Django 4.1.7 on 2023-03-19 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_alter_productmodal_product_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodal',
            old_name='product_uuid',
            new_name='product',
        ),
    ]
